class ImageWayConstants {
  static const Map<String, String> images = {
    "sunflower": 'assets/images/png/icons/sunflower.png',
    "potato": 'assets/images/png/icons/potato.png',
    "pumpkin": 'assets/images/png/icons/pumpkin.png',
    "carrot": 'assets/images/png/icons/carrot.png',
    "cabbage": 'assets/images/png/icons/cabbage.png',
    "soybean": 'assets/images/png/icons/soybean.png',
    "beetroot": 'assets/images/png/icons/beetroot.png',
    "cauliflower": 'assets/images/png/icons/cauliflower.png',
    "parsnip": 'assets/images/png/icons/parsnip.png',
    "eggplant": 'assets/images/png/icons/eggplant.png',
    "corn": 'assets/images/png/icons/corn.png',
    "radish": 'assets/images/png/icons/radish.png',
    "wheat": 'assets/images/png/icons/wheat.png',
    "kale": 'assets/images/png/icons/kale.png',
    "barley": 'assets/images/png/icons/barley.png',
    "tomato": 'assets/images/webp/tomato.webp',
    "lemon": 'assets/images/webp/lemon.webp',
    "blueberry": 'assets/images/png/icons/blueberry.png',
    "orange": 'assets/images/png/icons/orange.png',
    "apple": 'assets/images/png/icons/apple.png',
    "banana": 'assets/images/png/icons/banana.png',
    "grape": 'assets/images/webp/grape.webp',
    "rice": 'assets/images/webp/rice.webp',
    "olive": 'assets/images/webp/olive.webp',
    "wood": 'assets/images/png/icons/wood.png',
    "stone": 'assets/images/png/icons/stone.png',
    "iron": 'assets/images/png/icons/iron.png',
    "gold": 'assets/images/png/icons/gold.png',
    "crimstone": 'assets/images/png/icons/crimstone.png',
    "sunstone": 'assets/images/png/icons/sunstone.png',
    "egg": 'assets/images/png/icons/egg.png',
    "feather": 'assets/images/webp/feather.webp',
    "honey": 'assets/images/png/icons/honey.png',
    "milk": 'assets/images/webp/milk.webp',
    "leather": 'assets/images/webp/leather.webp',
    "wool": 'assets/images/webp/wool.webp',
    "merino_wool": 'assets/images/webp/merino_wool.webp',
    "oil": 'assets/images/webp/oil.webp',
    "seeds": 'assets/images/png/icons/seeds.png',
    "seed_plot": 'assets/images/png/icons/seed_plot.png',
    "tree_plot": 'assets/images/webp/tree_plot.webp',
    "stone_plot": 'assets/images/png/icons/stone_small.png',
    "iron_plot": 'assets/images/png/icons/iron_plot.png',
    "gold_plot": 'assets/images/png/icons/gold_plot.png',
    "crimstone_plot": 'assets/images/webp/crimstone_plot.webp',
    "sunstone_plot": 'assets/images/webp/sunstone_plot.webp',
    "oil_plot": 'assets/images/webp/oil_plot.webp',
    "fruit_plot": 'assets/images/png/icons/fruit_plot.png',
    "blue balloon flower": 'assets/images/png/icons/Blue Balloon Flower.png',
    "blue carnation": 'assets/images/png/icons/Blue Carnation.png',
    "blue cosmos": 'assets/images/png/icons/Blue Cosmos.png',
    "blue daffodil": 'assets/images/png/icons/Blue Daffodil.png',
    "blue lotus": 'assets/images/png/icons/Blue Lotus.png',
    "blue pansy": 'assets/images/png/icons/Blue Pansy.png',
    "celestial frostbloom": 'assets/images/png/icons/Celestial Frostbloom.png',
    "primula enigma": 'assets/images/png/icons/Primula Enigma.png',
    "prism petal": 'assets/images/png/icons/Prism Petal.png',
    "purple balloon flower":
        'assets/images/png/icons/Purple Balloon Flower.png',
    "purple carnation": 'assets/images/png/icons/Purple Carnation.png',
    "purple cosmos": 'assets/images/png/icons/Purple Cosmos.png',
    "purple daffodil": 'assets/images/png/icons/Purple Daffodil.png',
    "purple lotus": 'assets/images/png/icons/Purple Lotus.png',
    "purple pansy": 'assets/images/png/icons/Purple Pansy.png',
    "red balloon flower": 'assets/images/png/icons/Red Balloon Flower.png',
    "red carnation": 'assets/images/png/icons/Red Carnation.png',
    "red cosmos": 'assets/images/png/icons/Red Cosmos.png',
    "red daffodil": 'assets/images/png/icons/Red Daffodil.png',
    "red lotus": 'assets/images/png/icons/Red Lotus.png',
    "red pansy": 'assets/images/png/icons/Red Pansy.png',
    "white balloon flower": 'assets/images/png/icons/White Balloon Flower.png',
    "white carnation": 'assets/images/png/icons/White Carnation.png',
    "white cosmos": 'assets/images/png/icons/White Cosmos.png',
    "white daffodil": 'assets/images/png/icons/White Daffodil.png',
    "white lotus": 'assets/images/png/icons/White Lotus.png',
    "white pansy": 'assets/images/png/icons/White Pansy.png',
    "yellow balloon flower":
        'assets/images/png/icons/Yellow Balloon Flower.png',
    "yellow carnation": 'assets/images/png/icons/Yellow Carnation.png',
    "yellow cosmos": 'assets/images/png/icons/Yellow Cosmos.png',
    "yellow daffodil": 'assets/images/png/icons/Yellow Daffodil.png',
    "yellow lotus": 'assets/images/png/icons/Yellow Lotus.png',
    "yellow pansy": 'assets/images/png/icons/Yellow Pansy.png',
    "coin": 'assets/images/webp/coins.webp',
    "sfl": 'assets/images/webp/sfl.webp',
  };
}

String getImageWay(String imageName) {
  return ImageWayConstants.images[imageName.toLowerCase()] ?? '';
}
